<?php
session_start();
$error='';
if(isset($_POST['login'])){
$username=trim($_POST['uname']??'');$password=(string)($_POST['psw']??'');
if($username===''||$password===''){$error='Kullanıcı adı ve şifre zorunludur.';}else{require 'dbconfig.php';$stmt=$conn->prepare('SELECT username,name,password FROM patient WHERE username=? LIMIT 1');$stmt->bind_param('s',$username);$stmt->execute();$patient=$stmt->get_result()->fetch_assoc();$stmt->close();$valid=false;if($patient){$stored=(string)$patient['password'];$valid=password_verify($password,$stored);if(!$valid&&hash_equals($stored,$password)){$newHash=password_hash($password,PASSWORD_DEFAULT);$upgrade=$conn->prepare('UPDATE patient SET password=? WHERE username=? LIMIT 1');$upgrade->bind_param('ss',$newHash,$patient['username']);$upgrade->execute();$upgrade->close();$valid=true;}}if($valid){session_regenerate_id(true);$_SESSION['username']=$patient['username'];$_SESSION['user']=$patient['name'];header('Location: ulogin.php');exit;}$error='Kullanıcı adı veya şifre geçersiz.';$conn->close();}}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Appointment | Randevu Sistemi</title><link rel="stylesheet" href="main.css"><style>
.landing{min-height:100vh;display:flex;flex-direction:column;background:radial-gradient(circle at 85% 15%,#dbeafe 0,transparent 35%),linear-gradient(135deg,#f8fbff,#eef4fb)}.landing-header .header-inner{min-height:76px}.landing-main{flex:1;display:grid;place-items:center;padding:55px 20px}.landing-content{width:min(820px,100%);text-align:center}.landing-logo{width:72px;height:72px;margin:0 auto 21px;padding:13px;border-radius:21px;background:#fff;box-shadow:0 16px 38px rgba(25,45,80,.12)}.landing-logo img{width:100%;height:100%;object-fit:contain}.landing-content h1{margin-bottom:15px;font-size:clamp(38px,7vw,62px)}.landing-content .lead{max-width:650px;margin:0 auto 30px;font-size:18px}.landing-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.landing-actions .button{min-width:165px}.landing-footer{padding:18px;text-align:center}.landing-footer a{display:inline-block;color:#687386;font-size:12px;font-weight:750;margin:0 10px}.landing-footer a:hover{color:var(--primary)}.modal{position:fixed;inset:0;z-index:100;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(16,28,48,.52);backdrop-filter:blur(5px)}.modal.open{display:flex}.modal-content{width:min(460px,100%);max-height:calc(100vh - 36px);overflow:auto;border:1px solid var(--border);border-radius:20px;background:#fff;box-shadow:0 25px 75px rgba(16,28,48,.25)}.modal-head{display:flex;align-items:center;justify-content:space-between;padding:23px 25px 0}.modal-head h2{margin:0;font-size:23px}.modal-body{padding:23px 25px}.modal-footer{display:flex;justify-content:flex-end;gap:10px;padding:16px 25px 23px;border-top:1px solid var(--border)}.modal-footer .button{width:auto}.close{width:36px;height:36px;border:0;border-radius:50%;background:#f2f5f9;color:#566174;font-size:24px;cursor:pointer}.close:hover{background:#e6ebf2}.login-note{margin:0 0 20px}.login-error{margin-bottom:18px}.signup-modal{width:min(560px,100%)}.steps-image{display:block;width:min(280px,80%);max-height:180px;object-fit:contain;margin:0 auto 18px}.signup-copy{text-align:center}.signup-copy p:last-child{margin-bottom:0}@media(max-width:600px){.landing-main{padding:35px 16px}.landing-actions{flex-direction:column;width:min(320px,100%);margin:auto}.landing-actions .button{width:100%}.modal{padding:9px}.modal-content{border-radius:16px}.modal-head,.modal-body{padding-left:18px;padding-right:18px}.modal-footer{padding-left:18px;padding-right:18px;flex-direction:column-reverse}.modal-footer .button{width:100%}.landing-footer a{margin:4px 7px}}
</style></head><body class="landing">
<header class="site-header landing-header"><div class="header-inner"><a href="cover.php" class="brand"><img src="images/cal.png" alt="Takvim"><span>Appointment</span></a><nav><a class="active" href="cover.php">Ana Sayfa</a><a href="locateus.php">Bize Ulaşın</a></nav></div></header>
<main class="landing-main"><section class="landing-content"><div class="landing-logo"><img src="images/cal.png" alt="Appointment"></div><span class="eyebrow">ONLINE RANDEVU SİSTEMİ</span><h1>Sağlık randevunuzu kolayca yönetin.</h1><p class="lead">Doktorunuzu, kliniğinizi ve size uygun zamanı seçin. Randevunuzu tek bir ekrandan oluşturun ve takip edin.</p><div class="landing-actions"><button type="button" class="button" id="openLoginButton">Giriş Yap</button><button type="button" class="button secondary" id="openSignupButton">Yeni Hesap Oluştur</button></div></section></main>
<footer class="landing-footer"><a href="admin/alogin.php">Yönetici Girişi</a><a href="admin/mlogin.php">Manager Girişi</a><a href="Admin/dlogin.php">Doktor Girişi</a></footer>
<div id="loginModal" class="modal" role="dialog" aria-modal="true"><form class="modal-content" method="post" action="cover.php"><div class="modal-head"><h2>Hasta Girişi</h2><button type="button" class="close" id="closeLoginButton" aria-label="Kapat">&times;</button></div><div class="modal-body"><p class="login-note">Hasta hesabınızla giriş yaparak randevularınızı yönetin.</p><?php if($error!==''):?><div class="alert error login-error"><?php echo htmlspecialchars($error,ENT_QUOTES,'UTF-8');?></div><?php endif;?><div class="field"><label for="uname">Kullanıcı adı</label><input id="uname" type="text" name="uname" placeholder="Kullanıcı adınız" autocomplete="username" required></div><div class="field" style="margin-top:16px"><label for="psw">Şifre</label><input id="psw" type="password" name="psw" placeholder="Şifreniz" autocomplete="current-password" required></div></div><div class="modal-footer"><button type="button" class="button secondary" id="cancelLoginButton">Vazgeç</button><button type="submit" name="login" class="button">Giriş Yap</button></div></form></div>
<div id="signupModal" class="modal" role="dialog" aria-modal="true"><div class="modal-content signup-modal"><div class="modal-head"><h2>Yeni hesap oluştur</h2><button type="button" class="close" id="closeSignupButton" aria-label="Kapat">&times;</button></div><div class="modal-body signup-copy"><img class="steps-image" src="images/steps.png" alt="Randevu oluşturma adımları"><p><strong>Hesabınızı oluşturun → Tarihinizi seçin → Randevunuzu oluşturun</strong></p><p>Randevu almak hiç bu kadar kolay olmamıştı.</p></div><div class="modal-footer"><button type="button" class="button secondary" id="cancelSignupButton">Vazgeç</button><a href="signup.php" class="button">Kayıt Ol</a></div></div></div>
<script>(function(){function $(id){return document.getElementById(id)}function open(m){m.classList.add('open')}function close(m){m.classList.remove('open')}var l=$('loginModal'),s=$('signupModal');$('openLoginButton').onclick=function(){open(l);$('uname').focus()};$('openSignupButton').onclick=function(){open(s)};$('closeLoginButton').onclick=$('cancelLoginButton').onclick=function(){close(l)};$('closeSignupButton').onclick=$('cancelSignupButton').onclick=function(){close(s)};[l,s].forEach(function(m){m.onclick=function(e){if(e.target===m)close(m)}});document.onkeydown=function(e){if(e.key==='Escape'){close(l);close(s)}}})();</script></body></html>