<?php
session_start();
require_once 'dbconfig.php';
if (!isset($_SESSION['mgrid'])) { header('Location: mlogin.php'); exit; }
$mid=(int)$_SESSION['mgrid']; $message=''; $did=(int)($_POST['doctor']??0); $dateselected=$_POST['dateselected']??'';
$doctors=$conn->prepare('SELECT DISTINCT d.DID,d.Name FROM doctor d INNER JOIN doctor_availability da ON da.DID=d.DID INNER JOIN manager_clinic mc ON mc.CID=da.CID WHERE mc.MID=? ORDER BY d.Name ASC');
$doctors->bind_param('i',$mid); $doctors->execute(); $doctorResult=$doctors->get_result();
if(isset($_POST['submit2'])){
 $appointmentIds=$_POST['appointment_id']??[]; $statuses=$_POST['status']??[]; $count=min(count($appointmentIds),count($statuses)); $allowed=['Bekliyor','Onaylandı','Tamamlandı','İptal Edildi'];
 $update=$conn->prepare("UPDATE book b INNER JOIN manager_clinic mc ON mc.CID=b.CID SET b.Status=?, b.active_slot_key=CASE WHEN ? IN ('İptal Edildi','Tamamlandı') THEN NULL ELSE b.active_slot_key END WHERE b.appointment_id=? AND mc.MID=?");
 for($j=0;$j<$count;$j++){ $appointmentId=(int)$appointmentIds[$j]; $status=trim($statuses[$j]); if($appointmentId<=0||!in_array($status,$allowed,true)) continue; $update->bind_param('ssii',$status,$status,$appointmentId,$mid); if($update->execute() && $update->affected_rows>0){ $message.='Randevu #'.$appointmentId.' : Durum başarıyla güncellendi.<br>'; }} $update->close();
}
$rows=[];
if(isset($_POST['submit'])&&$did>0&&$dateselected!==''){
 $query=$conn->prepare('SELECT b.appointment_id,b.Username,b.Fname,b.DOV,b.Timestamp,b.Status FROM book b INNER JOIN manager_clinic mc ON mc.CID=b.CID WHERE b.DOV=? AND b.DID=? AND mc.MID=? ORDER BY b.Timestamp ASC');
 $query->bind_param('sii',$dateselected,$did,$mid); $query->execute(); $result=$query->get_result(); while($row=$result->fetch_assoc()){$rows[]=$row;} $query->close();
}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Randevu Durumu</title><link rel="stylesheet" href="main.css"><style>table{width:100%;border-collapse:collapse;border:4px solid black;padding:1px;font-size:25px}th{border:1px solid black;background-color:#4CAF50;color:white;text-align:left}tr,td{border:1px solid black;background-color:white;color:black}</style></head>
<body style="background-image:url(mgrchange.jpg)"><div class="header"><ul><li style="float:left;border-right:none"><a href="mgrmenu.php" class="logo"><img src="../images/cal.png" width="30" height="30" alt="Takvim"><strong> Appointment </strong></a></li><li><a href="mgrmenu.php">Home</a></li></ul></div><div class="sucontainer">
<?php if($message!==''):?><div><?php echo $message;?></div><?php endif;?>
<form action="changebookingstatus.php" method="post"><label style="font-size:20px"><b>Doktor:</b></label><br><select name="doctor" class="demoInputBox" style="width:100%;height:35px;border-radius:9px" required><option value="">Doktor seçin</option><?php while($doctor=$doctorResult->fetch_assoc()):?><option value="<?php echo (int)$doctor['DID'];?>" <?php echo $did===(int)$doctor['DID']?'selected':'';?>><?php echo htmlspecialchars('Dr. '.$doctor['Name'],ENT_QUOTES,'UTF-8');?></option><?php endwhile;?></select><br><label><b>Tarih:</b></label><br><input type="date" name="dateselected" value="<?php echo htmlspecialchars($dateselected,ENT_QUOTES,'UTF-8');?>" required><br><br><button type="submit" name="submit" value="Submit">Randevuları Getir</button></form>
<?php if(isset($_POST['submit'])&&$did>0&&$dateselected!==''):?><form action="changebookingstatus.php" method="post"><input type="hidden" name="doctor" value="<?php echo $did;?>"><input type="hidden" name="dateselected" value="<?php echo htmlspecialchars($dateselected,ENT_QUOTES,'UTF-8');?>"><table><tr><th>Randevu</th><th>Kullanıcı</th><th>Hasta</th><th>Tarih</th><th>Timestamp</th><th>Durum</th></tr><?php if(!$rows):?><tr><td colspan="6">Bu tarihte randevu bulunamadı.</td></tr><?php else:foreach($rows as $row):?><tr><td>#<?php echo (int)$row['appointment_id'];?><input type="hidden" name="appointment_id[]" value="<?php echo (int)$row['appointment_id'];?>"></td><td><?php echo htmlspecialchars($row['Username'],ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($row['Fname'],ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($row['DOV'],ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($row['Timestamp'],ENT_QUOTES,'UTF-8');?></td><td><select name="status[]"><?php foreach(['Bekliyor','Onaylandı','Tamamlandı','İptal Edildi'] as $option):?><option value="<?php echo htmlspecialchars($option,ENT_QUOTES,'UTF-8');?>" <?php echo $row['Status']===$option?'selected':'';?>><?php echo htmlspecialchars($option,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></td></tr><?php endforeach;endif;?></table><?php if($rows):?><button type="submit" name="submit2" value="Submit">Değişiklikleri Kaydet</button><?php endif;?></form><?php endif;?></div></body></html>